Resources:
  WebServer:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0c55b159cbfafe1f0"
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable HTTP access to the web server"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
  DataVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      Size: 50
  LogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "my-app-logs"
